version: '3'

services:
  -sequelize:
    build: ./softex-bookstore
    ports:
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=bookstore
      - DB_HOST=db
    volumes:
      - ./softex-bookstore:/app-crud
    container_name: bookstore_crud
    restart: always
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: always
